// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/[name].tsx";
import * as $1 from "./routes/_404.tsx";
import * as $2 from "./routes/_middleware.tsx";
import * as $3 from "./routes/about.jsx";
import * as $4 from "./routes/api/joke.ts";
import * as $5 from "./routes/countdown/index.tsx";
import * as $6 from "./routes/hello/index.tsx";
import * as $7 from "./routes/index.tsx";
import * as $8 from "./routes/users/_middleware.tsx";
import * as $9 from "./routes/users/github.tsx";
import * as $$0 from "./islands/Countdown.tsx";
import * as $$1 from "./islands/SearchGithubUser.tsx";

const manifest = {
  routes: {
    "./routes/[name].tsx": $0,
    "./routes/_404.tsx": $1,
    "./routes/_middleware.tsx": $2,
    "./routes/about.jsx": $3,
    "./routes/api/joke.ts": $4,
    "./routes/countdown/index.tsx": $5,
    "./routes/hello/index.tsx": $6,
    "./routes/index.tsx": $7,
    "./routes/users/_middleware.tsx": $8,
    "./routes/users/github.tsx": $9,
  },
  islands: {
    "./islands/Countdown.tsx": $$0,
    "./islands/SearchGithubUser.tsx": $$1,
  },
  baseUrl: import.meta.url,
};

export default manifest;
